<?php

// This file is automatically generated and modified by phpMyBackupPro v.2.2

$CONF['sql_user']="sj_timesheet";
$CONF['sql_passwd']="sj_timesheet";
$CONF['sql_host']="vertigo";
$CONF['sql_db']="skipjack_timesheet";
$CONF['ftp_use']="0";
$CONF['allow_dir_backup']="0";
$CONF['email_use']="1";
$CONF['sitename']="Timesheet";
$CONF['lang']="english";
$CONF['import_error']="1";
$CONF['no_login']="1";
$CONF['login']="0";
$CONF['dir_backup']="1";
$CONF['dir_rec']="1";
$CONF['email']="ddiderson@yahoo.fr";
$CONF['ftp_pasv']="0";
$CONF['ftp_del']="0";
$CONF['ftp_server']="ps15326.dreamhostps.com";
$CONF['ftp_user']="connect123";
$CONF['ftp_passwd']="connect531";
$CONF['ftp_path']="example/";
$CONF['ftp_port']="21";
$CONF['date']="%b %d %Y %H:%M";
$CONF['del_time']="7";
$CONF['del_number']="5";
$CONF['timelimit']="600";
$CONF['confirm']="1";
$CONF['stylesheet']="standard";

$PMBP_SYS_VAR['last_scheduled']="";
$PMBP_SYS_VAR['this_login']="31.05.2012 16:24 Uhr (IP: 192.168.0.9)";
$PMBP_SYS_VAR['last_login']="31.05.2012 16:23 Uhr (IP: 192.168.0.9)";
$PMBP_SYS_VAR['dir_lists']="1";
$PMBP_SYS_VAR['memory_limit']="8000000";
$PMBP_SYS_VAR['except_tables']="";
$PMBP_SYS_VAR['scheduled_debug']="0";
$PMBP_SYS_VAR['schedule_all_dbs']="0";
$PMBP_SYS_VAR['ftp_timeout']="10";
$PMBP_SYS_VAR['dir_email_backup']="0";
$PMBP_SYS_VAR['F_dbs']="skipjack_timesheet";
$PMBP_SYS_VAR['F_comment']="";
$PMBP_SYS_VAR['F_tables']="on";
$PMBP_SYS_VAR['F_data']="on";
$PMBP_SYS_VAR['F_drop']="on";
$PMBP_SYS_VAR['F_compression']="";
$PMBP_SYS_VAR['F_ftp_dirs']="../phpmybackup/export/";
$PMBP_SYS_VAR['F_ftp_dirs_2']="";
$PMBP_SYS_VAR['F_packed']="";
$PMBP_SYS_VAR['F_updates']="1";
$PMBP_SYS_VAR['F_ffadd']="1";
$PMBP_SYS_VAR['EXS_scheduled_file']="???.php";
$PMBP_SYS_VAR['EXS_scheduled_dir']="";
$PMBP_SYS_VAR['EXS_period']="*0";
$PMBP_SYS_VAR['C_disable_config']="0";
$PMBP_SYS_VAR['C_disable_sqlquery']="0";
$PMBP_SYS_VAR['security_key']="0833f89e499d67eaa2b307ce084b3015";

?>